### ISSUE TITLE
ModuleNotFoundError: No module named 'flask' - in the latest docker image

### ISSUE THREAD

**Issue by zerolabnet** [ramonvc/freegpt-webui#115]
Error in the latest docker image:

```
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/./run.py", line 1, in <module>
    from server.bp import bp
  File "/app/server/bp.py", line 1, in <module>
    from flask import Blueprint
```

**Comment by gosvoh** [comment]
Error still remain

**Comment by zken2002** [comment]
Same problem
