### ISSUE TITLE
<!doctype html> <html lang=en> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

### ISSUE THREAD

**Issue by MackyCoders** [ramonvc/freegpt-webui#163]
Bruh

**Comment by ramonvc** [comment]
Without more details I can't help

**Comment by HeroBarry** [comment]
`Error on request:
Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/werkzeug/serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "/app/venv/lib/python3.10/site-packages/werkzeug/serving.py", line 327, in execute
    for data in application_iter:
  File "/app/venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 289, in __next__
    return self._next()
  File "/app/venv/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/app/venv/lib/python3.10/site-packages/flask/helpers.py", line 118, in generator
    yield from gen
  File "/app/server/backend.py", line 139, in generate_stream
    yield from response
  File "/app/g4f/Provider/Providers/DeepAi.py", line 40, in _create_completion
    r.raise_for_status()
  File "/app/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.deepai.org/chat_response`  

@ramonvc  docker logs Error 


api.deepai.org @MackyCoders  404

**Comment by kukuos** [comment]
亲测用的日本亚马逊云docker搭建不需要开代理可以正常使用，香港不知道没有测过

**Comment by HeroBarry** [comment]
> 亲测用的日本亚马逊云docker搭建不需要开代理可以正常使用，香港不知道没有测过

我这是美国硅谷服务器  腾讯云的  GPT4可以访问 不过已经变得智障起来了 GPT3.5访问不到了

**Comment by HeroBarry** [comment]
After updating the Docker image, it seems to be accessible @ramonvc  

@MackyCoders try update Docker image

**Comment by MackyCoders** [comment]
i did it with PIP not docker

**Comment by HeroBarry** [comment]
更新代码试过了么？@MackyCoders

**Comment by MackyCoders** [comment]
Idu what u are saying @HeroBarry
