### ISSUE TITLE
ModuleNotFoundError: No module named 'execjs'

### ISSUE THREAD

**Issue by cctvoh** [ramonvc/freegpt-webui#166]
When I use "python run.py", an issue happen(as follows), what should I do?

Traceback (most recent call last):
  File "c:\Users\Yuyue\freegpt-webui\run.py", line 5, in <module>
    from server.backend import Backend_Api
  File "c:\Users\Yuyue\freegpt-webui\server\backend.py", line 3, in <module>
    from g4f import ChatCompletion
  File "c:\Users\Yuyue\freegpt-webui\g4f\__init__.py", line 2, in <module>
    from . import Provider
  File "c:\Users\Yuyue\freegpt-webui\g4f\Provider\__init__.py", line 2, in <module>
    from .Providers import (
  File "c:\Users\Yuyue\freegpt-webui\g4f\Provider\Providers\Vercel.py", line 4, in <module>
    import execjs
ModuleNotFoundError: No module named 'execjs'

**Comment by ramonvc** [comment]
Did you install the dependencies?

**Comment by cctvoh** [comment]
> Did you install the dependencies?

Yes I have. what else dependencies should I install ? when I executed "pip install -r requirements.txt", there was no issues occurred.
