### ISSUE TITLE
Error trying to run run.py file

### ISSUE THREAD

**Issue by misanthropeeee** [ramonvc/freegpt-webui#182]
After the requirements.txt installation, nothing works and an error with the module called "babel" appears
`C:\Users\admin\Desktop\chat-gpt\freegpt-webui>py run.py
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\chat-gpt\freegpt-webui\run.py", line 22, in <module>
    create_babel(app)
  File "C:\Users\admin\Desktop\chat-gpt\freegpt-webui\server\babel.py", line 24, in create_babel
    compile_translations()
  File "C:\Users\admin\Desktop\chat-gpt\freegpt-webui\server\babel.py", line 39, in compile_translations
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Cannot find file
`

**Comment by misanthropeeee** [comment]
The problem with the error was resolved by adding the path to Python Scripts folder to the Path. The AI demo on the website https://chat.ramxn.dev/ helped me with this. 👍

**Comment by misanthropeeee** [comment]
The problem with the error was resolved by adding the path to Python Scripts folder to the Path. The AI demo on the website https://chat.ramxn.dev/ helped me with this. 👍
