### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by rufatkiu** [ramonvc/freegpt-webui#31]
<!doctype html> <html lang="en"> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

**Comment by 7biz** [comment]
Now I also started getting an error, yesterday everything worked.
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

**Comment by Am0rphous** [comment]
I experienced the same problem @rufatkiu and @7biz  . Somehow it fixed itself after I pulled updates. Hopefully this will help you as well:
````
cd freegpt-webui
git pull
pip install -r requirements.txt
python run.py
````

**Comment by final999** [comment]
已更新到最新，依然有这个错误。

**Comment by final999** [comment]
2023-07-15 21:42:49   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
2023-07-15 21:42:49     ) = cls.__prepare_create_request(
2023-07-15 21:42:49   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
2023-07-15 21:42:49     requestor = api_requestor.APIRequestor(
2023-07-15 21:42:49   File "/root/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 138, in __init__
2023-07-15 21:42:49     self.api_key = key or util.default_api_key()
2023-07-15 21:42:49   File "/root/.local/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
2023-07-15 21:42:49     raise openai.error.AuthenticationError(
2023-07-15 21:42:49 openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
2023-07-15 21:43:04 172.17.0.1 - - [15/Jul/2023 13:43:04] "POST /backend-api/v2/conversation HTTP/1.1" 500 -
2023-07-15 21:43:04 Error on request:
2023-07-15 21:43:04 Traceback (most recent call last):
2023-07-15 21:43:04   File "/root/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 364, in run_wsgi
2023-07-15 21:43:04     execute(self.server.app)
2023-07-15 21:43:04   File "/root/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 327, in execute
2023-07-15 21:43:04     for data in application_iter:
2023-07-15 21:43:04   File "/root/.local/lib/python3.10/site-packages/werkzeug/wsgi.py", line 289, in __next__
2023-07-15 21:43:04     return self._next()
2023-07-15 21:43:04   File "/root/.local/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
2023-07-15 21:43:04     for item in iterable:
2023-07-15 21:43:04   File "/app/server/backend.py", line 155, in generate_stream
2023-07-15 21:43:04     yield from response
2023-07-15 21:43:04   File "/app/g4f/Provider/Providers/Chimera.py", line 36, in _create_completion
2023-07-15 21:43:04     response = openai.ChatCompletion.create(
2023-07-15 21:43:04   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
2023-07-15 21:43:04     return super().create(*args, **kwargs)
2023-07-15 21:43:04   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
2023-07-15 21:43:04     ) = cls.__prepare_create_request(
2023-07-15 21:43:04   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
2023-07-15 21:43:04     requestor = api_requestor.APIRequestor(
2023-07-15 21:43:04   File "/root/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 138, in __init__
2023-07-15 21:43:04     self.api_key = key or util.default_api_key()
2023-07-15 21:43:04   File "/root/.local/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
2023-07-15 21:43:04     raise openai.error.AuthenticationError(
2023-07-15 21:43:04 openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
2023-07-15 21:43:18 172.17.0.1 - - [15/Jul/2023 13:43:18] "POST /backend-api/v2/conversation HTTP/1.1" 500 -
2023-07-15 21:43:18 Error on request:
2023-07-15 21:43:18 Traceback (most recent call last):
2023-07-15 21:43:18   File "/root/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 364, in run_wsgi
2023-07-15 21:43:18     execute(self.server.app)
2023-07-15 21:43:18   File "/root/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 327, in execute
2023-07-15 21:43:18     for data in application_iter:
2023-07-15 21:43:18   File "/root/.local/lib/python3.10/site-packages/werkzeug/wsgi.py", line 289, in __next__
2023-07-15 21:43:18     return self._next()
2023-07-15 21:43:18   File "/root/.local/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
2023-07-15 21:43:18     for item in iterable:
2023-07-15 21:43:18   File "/app/server/backend.py", line 155, in generate_stream
2023-07-15 21:43:18     yield from response
2023-07-15 21:43:18   File "/app/g4f/Provider/Providers/Chimera.py", line 36, in _create_completion
2023-07-15 21:43:18     response = openai.ChatCompletion.create(
2023-07-15 21:43:18   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
2023-07-15 21:43:18     return super().create(*args, **kwargs)
2023-07-15 21:43:18   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
2023-07-15 21:43:18     ) = cls.__prepare_create_request(
2023-07-15 21:43:18   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
2023-07-15 21:43:18     requestor = api_requestor.APIRequestor(
2023-07-15 21:43:18   File "/root/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 138, in __init__
2023-07-15 21:43:18     self.api_key = key or util.default_api_key()
2023-07-15 21:43:18   File "/root/.local/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
2023-07-15 21:43:18     raise openai.error.AuthenticationError(
2023-07-15 21:43:18 openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
2023-07-15 21:43:36 172.17.0.1 - - [15/Jul/2023 13:43:36] "POST /backend-api/v2/conversation HTTP/1.1" 500 -
2023-07-15 21:43:36 Error on request:
2023-07-15 21:43:36 Traceback (most recent call last):
2023-07-15 21:43:36   File "/root/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 364, in run_wsgi
2023-07-15 21:43:36     execute(self.server.app)
2023-07-15 21:43:36   File "/root/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 327, in execute
2023-07-15 21:43:36     for data in application_iter:
2023-07-15 21:43:36   File "/root/.local/lib/python3.10/site-packages/werkzeug/wsgi.py", line 289, in __next__
2023-07-15 21:43:36     return self._next()
2023-07-15 21:43:36   File "/root/.local/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
2023-07-15 21:43:36     for item in iterable:
2023-07-15 21:43:36   File "/app/server/backend.py", line 155, in generate_stream
2023-07-15 21:43:36     yield from response
2023-07-15 21:43:36   File "/app/g4f/Provider/Providers/Chimera.py", line 36, in _create_completion
2023-07-15 21:43:36     response = openai.ChatCompletion.create(
2023-07-15 21:43:36   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
2023-07-15 21:43:36     return super().create(*args, **kwargs)
2023-07-15 21:43:36   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
2023-07-15 21:43:36     ) = cls.__prepare_create_request(
2023-07-15 21:43:36   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
2023-07-15 21:43:36     requestor = api_requestor.APIRequestor(
2023-07-15 21:43:36   File "/root/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 138, in __init__
2023-07-15 21:43:36     self.api_key = key or util.default_api_key()
2023-07-15 21:43:36   File "/root/.local/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
2023-07-15 21:43:36     raise openai.error.AuthenticationError(
2023-07-15 21:43:36 openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
2023-07-15 21:44:08 172.17.0.1 - - [15/Jul/2023 13:44:08] "POST /backend-api/v2/conversation HTTP/1.1" 400 -
2023-07-15 21:44:35 172.17.0.1 - - [15/Jul/2023 13:44:35] "POST /backend-api/v2/conversation HTTP/1.1" 400 -
2023-07-15 21:44:53 172.17.0.1 - - [15/Jul/2023 13:44:53] "POST /backend-api/v2/conversation HTTP/1.1" 500 -
2023-07-15 21:44:53 Error on request:
2023-07-15 21:44:53 Traceback (most recent call last):
2023-07-15 21:44:53   File "/root/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 364, in run_wsgi
2023-07-15 21:44:53     execute(self.server.app)
2023-07-15 21:44:53   File "/root/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 327, in execute
2023-07-15 21:44:53     for data in application_iter:
2023-07-15 21:44:53   File "/root/.local/lib/python3.10/site-packages/werkzeug/wsgi.py", line 289, in __next__
2023-07-15 21:44:53     return self._next()
2023-07-15 21:44:53   File "/root/.local/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
2023-07-15 21:44:53     for item in iterable:
2023-07-15 21:44:53   File "/app/server/backend.py", line 155, in generate_stream
2023-07-15 21:44:53     yield from response
2023-07-15 21:44:53   File "/app/g4f/Provider/Providers/Chimera.py", line 36, in _create_completion
2023-07-15 21:44:53     response = openai.ChatCompletion.create(
2023-07-15 21:44:53   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
2023-07-15 21:44:53     return super().create(*args, **kwargs)
2023-07-15 21:44:53   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
2023-07-15 21:44:53     ) = cls.__prepare_create_request(
2023-07-15 21:44:53   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
2023-07-15 21:44:53     requestor = api_requestor.APIRequestor(
2023-07-15 21:44:53   File "/root/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 138, in __init__
2023-07-15 21:44:53     self.api_key = key or util.default_api_key()
2023-07-15 21:44:53   File "/root/.local/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
2023-07-15 21:44:53     raise openai.error.AuthenticationError(
2023-07-15 21:44:53 openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
2023-07-15 21:45:07 172.17.0.1 - - [15/Jul/2023 13:45:07] "POST /backend-api/v2/conversation HTTP/1.1" 500 -
2023-07-15 21:45:07 Error on request:
2023-07-15 21:45:07 Traceback (most recent call last):
2023-07-15 21:45:07   File "/root/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 364, in run_wsgi
2023-07-15 21:45:07     execute(self.server.app)
2023-07-15 21:45:07   File "/root/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 327, in execute
2023-07-15 21:45:07     for data in application_iter:
2023-07-15 21:45:07   File "/root/.local/lib/python3.10/site-packages/werkzeug/wsgi.py", line 289, in __next__
2023-07-15 21:45:07     return self._next()
2023-07-15 21:45:07   File "/root/.local/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
2023-07-15 21:45:07     for item in iterable:
2023-07-15 21:45:07   File "/app/server/backend.py", line 155, in generate_stream
2023-07-15 21:45:07     yield from response
2023-07-15 21:45:07   File "/app/g4f/Provider/Providers/Chimera.py", line 36, in _create_completion
2023-07-15 21:45:07     response = openai.ChatCompletion.create(
2023-07-15 21:45:07   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
2023-07-15 21:45:07     return super().create(*args, **kwargs)
2023-07-15 21:45:07   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
2023-07-15 21:45:07     ) = cls.__prepare_create_request(
2023-07-15 21:45:07   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
2023-07-15 21:45:07     requestor = api_requestor.APIRequestor(
2023-07-15 21:45:07   File "/root/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 138, in __init__
2023-07-15 21:45:07     self.api_key = key or util.default_api_key()
2023-07-15 21:45:07   File "/root/.local/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
2023-07-15 21:45:07     raise openai.error.AuthenticationError(
2023-07-15 21:45:07 openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
2023-07-15 21:45:33 172.17.0.1 - - [15/Jul/2023 13:45:33] "POST /backend-api/v2/conversation HTTP/1.1" 500 -
2023-07-15 21:45:33 Error on request:
2023-07-15 21:45:33 Traceback (most recent call last):
2023-07-15 21:45:33   File "/root/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 364, in run_wsgi
2023-07-15 21:45:33     execute(self.server.app)
2023-07-15 21:45:33   File "/root/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 327, in execute
2023-07-15 21:45:33     for data in application_iter:
2023-07-15 21:45:33   File "/root/.local/lib/python3.10/site-packages/werkzeug/wsgi.py", line 289, in __next__
2023-07-15 21:45:33     return self._next()
2023-07-15 21:45:33   File "/root/.local/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
2023-07-15 21:45:33     for item in iterable:
2023-07-15 21:45:33   File "/app/server/backend.py", line 155, in generate_stream
2023-07-15 21:45:33     yield from response
2023-07-15 21:45:33   File "/app/g4f/Provider/Providers/Chimera.py", line 36, in _create_completion
2023-07-15 21:45:33     response = openai.ChatCompletion.create(
2023-07-15 21:45:33   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
2023-07-15 21:45:33     return super().create(*args, **kwargs)
2023-07-15 21:45:33   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
2023-07-15 21:45:33     ) = cls.__prepare_create_request(
2023-07-15 21:45:33   File "/root/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
2023-07-15 21:45:33     requestor = api_requestor.APIRequestor(
2023-07-15 21:45:33   File "/root/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 138, in __init__
2023-07-15 21:45:33     self.api_key = key or util.default_api_key()
2023-07-15 21:45:33   File "/root/.local/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
2023-07-15 21:45:33     raise openai.error.AuthenticationError(
2023-07-15 21:45:33 openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
2023-07-15 21:47:12 172.17.0.1 - - [15/Jul/2023 13:47:12] "GET /assets/img/favicon-32x32.png HTTP/1.1" 304 -
2023-07-15 21:47:12 172.17.0.1 - - [15/Jul/2023 13:47:12] "GET /assets/img/favicon-32x32.png HTTP/1.1" 304 -
